const baseUrl = 'http://172.16.5.78:8082';

export const login = baseUrl + '/login';
export const apart = baseUrl + '/apart';
export const user = baseUrl + '/user';
export const getAllApart = baseUrl + '/get/all/apart';
export const createUser = baseUrl + '/public/create/user';
export const registerUserHouse = baseUrl + '/userhouse';
export const createComplaint = baseUrl + '/complaint';
export const getAllComplaint = baseUrl + '/get/all/complaint';
export const getAllComplaintManager = baseUrl + '/get/all/manager/complaint';
export const sendUuidForApart = baseUrl + '/send/uuid/for/apart';
export const createTool = baseUrl + '/tool';
export const getReservations = baseUrl + '/get/reservations';
export const createReservation = baseUrl + '/reservation';
export const getTools = baseUrl + '/get/tools';
export const smartDevice = baseUrl + '/smart/device';
export const complaintTypeWorkingOn = baseUrl + '/complaint/working/on';
export const complaintTypeSolved = baseUrl + '/complaint/solved';