server:
  port: ${SERVER_PORT:8082}
spring:
  application:
    name: Homey #Re-Desk
  profiles:
    active: ${SPRING_PROFILE:local}
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/homey}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:123}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail.default-encoding: UTF-8
  mail.host: smtp.gmail.com
  mail.username: homeydestek@gmail.com
  mail.password: HomeyDestek2021
  mail.port: 587
  mail.protocol: smtp
  mail.test-connection: false
  mail.properties.mail.smtp.auth: true
  mail.properties.mail.smtp.starttls.enable: true
  mail.properties.mail.smtp.ssl.trust: smtp.gmail.com